appclinica/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.urls import path, include
#from login.views import *
from appatencion.views import menuView, opcionesView
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('appatencion/', include('appatencion.urls')),
    path('menu/', login_required(menuView.as_view()), name='menu'),
    #--------------------------------------- login
    path('', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('opciones/', opcionesView.as_view(), name='opciones'),
    path('base/', include('appcore.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

appcore/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import * #PacienteView, CrearPacienteView, EditarPacienteView, EliminarPacienteView, DoctorView, EditarDoctorView, EliminarDoctorView, CrearDoctorView, IndexView
app_name = 'base'
urlpatterns = [
    path('paciente/', PacienteView.as_view(), name='paciente'),
    path('crear_paciente/', CrearPacienteView.as_view(), name='crear_paciente'),
    path('editar_paciente/<int:pk>/',
         EditarPacienteView.as_view(), name='editar_paciente'),
    path('eliminar_paciente/<int:pk>/',
         EliminarPacienteView.as_view(), name='eliminar_paciente'),

    path('cita/', CitaView.as_view(), name='cita'),
    path('crear_cita/', CrearCitaView.as_view(), name='crear_cita'),
    path('editar_cita/<int:pk>/',
         EditarCitaView.as_view(), name='editar_cita'),
    path('eliminar_cita/<int:pk>/',
         EliminarCitaView.as_view(), name='eliminar_cita'),


    path('signos/', SignosView.as_view(), name='signos'),
    path('crear_signo/',
         crearSignoView.as_view(), name='crear_signo'),
    path('editar_signo/<int:pk>/',
         EditarSignoView.as_view(), name='editar_signo'),


     path('', IndexView.as_view(), name='index'),  
     path('doctor_view/', login_required(DoctorView.as_view()), name='doctor_view'), 
     path('doctor/', CrearDoctorView.as_view(), name='doctor'), 
     path('doctor_edit/<int:pk>/', EditarDoctorView.as_view(), name='doctor_edit'),
     path('doctor_delete/<int:pk>/', EliminarDoctorView.as_view(), name='doctor_delete'),

]

login/urls.py
from django.contrib import admin
from django.urls import path
from login.views import LoginView
from django.conf import settings
app_name = "login"
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
]

appcore/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, date


class Provincia(models.Model):
    descripcion = models.CharField(verbose_name='Descripcion', max_length=100)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Provincia'
        verbose_name_plural = 'Provincias'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Ciudad(models.Model):
    provincia = models.ForeignKey(Provincia, on_delete=models.PROTECT)
    descripcion = models.CharField(verbose_name='Descripcion', max_length=100)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Ciudad'
        verbose_name_plural = 'Ciudades'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Profesion(models.Model):
    descripcion = models.CharField(
        verbose_name='Descripcion', max_length=100, unique=True)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Profesion'
        verbose_name_plural = 'Profesiones'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Titulo(models.Model):
    descripcion = models.CharField(
        verbose_name='Descripcion', max_length=100, unique=True)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Titulo'
        verbose_name_plural = 'Titulos'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Persona(models.Model):
    tipo_sexo = (('N', 'Ninguno'), ('M', 'Masculino'), ('F', 'Femenino'))
    estado_civil = (('S', 'Soltero'), ('C', 'Casado'),
                    ('D', 'Divorciado'), ('V', 'Viudo'), ('U', 'Union'))
    cedula = models.CharField('Cedula', max_length=13, unique=True)
    nombre = models.CharField(max_length=100, verbose_name='Nombres')
    apellido = models.CharField(max_length=100, verbose_name='Apellidos')
    nacimiento = models.DateField('Fecha Nacimiento', blank=True, null=True)
    sexo = models.CharField('sexo', choices=tipo_sexo,
                            default='N', max_length=1)
    civil = models.CharField(
        'Estado civil', choices=estado_civil, default='S', max_length=1)
    profesion = models.ManyToManyField(Profesion)
    titulo = models.ManyToManyField(Titulo)
    provincia = models.ForeignKey(
        Provincia, on_delete=models.PROTECT, blank=True, null=True)
    ciudad = models.ForeignKey(
        Ciudad, on_delete=models.PROTECT, blank=True, null=True)
    direccion = models.CharField(
        'Direccion', max_length=100, blank=True, null=True)
    telefono = models.CharField(
        'Telefono', max_length=100, blank=True, null=True)
    email = models.EmailField('Correo', max_length=100, blank=True, null=True)
    foto = models.ImageField('Foto', upload_to='fotos/', blank=True, null=True)

    class Meta:
        abstract = True

    def get_foto(self):
        try:
            return str(self.foto.url)
        except:
            pass
        return None


class Sangre(models.Model):
    tipo = models.CharField('Tipo de Sangre', max_length=20, unique=True)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Tipo de Sangre'
        verbose_name_plural = 'Tipos de Sangre'

    def __str__(self):
        return '{}'.format(self.tipo)


class Paciente(Persona):
    sangre = models.ForeignKey(
        Sangre, on_delete=models.PROTECT, blank=True, null=True)
    hijos = models.IntegerField('No.hijos', default=0)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'

    def __str__(self):
        return '{}'.format(self.nombre)


class Horario(models.Model):
    d_semana = {(0, 'Domingo'), (1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'),
                (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')}
    dia = models.IntegerField('Dia', choices=d_semana, default=1)
    desde = models.TimeField('Desde', blank=True, null=True)
    hasta = models.TimeField('Hasta', blank=True, null=True)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Dia'
        verbose_name_plural = 'Dias'

    def __str__(self):
        return '{}'.format(self.dia)


class Doctor(Persona):
    consultoria = models.CharField(max_length=200)
    lugar = models.CharField(
        verbose_name='Direccion de Consultorio', max_length=100)
    logo = models.ImageField(
        verbose_name='Logo', upload_to='Logos/', blank=True, null=True)
    horario = models.ManyToManyField(Horario)
    registro = models.CharField(verbose_name='Registro Medico', max_length=50)
    duracion = models.IntegerField(
        verbose_name='Duracion de Consulta', default=30)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Doctor'
        verbose_name_plural = 'Doctores'

    def __str__(self):
        return '{}'.format(self.nombre)


class Agenda(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.PROTECT)
    doctor = models.ForeignKey(Doctor, on_delete=models.PROTECT)
    fecha = models.DateField(
        'Fecha de Agenda', blank=True, null=True)
    hora = models.TimeField('Hora', default=datetime.now().time())
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Agenda'
        verbose_name_plural = 'Agendas'

    def __str__(self):
        return '{} {}'.format(self.paciente.nombre, self.paciente.apellido)


# ---------------------------------------------------------------------Sintomas
class Sintoma(models.Model):
    descripcion = models.CharField('Sintoma', max_length=100)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Sintoma'
        verbose_name_plural = 'Sintomas'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Diagnostico(models.Model):
    codigo = models.CharField('Codigo', max_length=100)
    descripcion = models.CharField('Diagnostico', max_length=100)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Diagnostico'
        verbose_name_plural = 'Diagnosticos'

    def __str__(self):
        return '{}'.format(self.descripcion)


class SignosVitales(models.Model):
    paciente = models.ForeignKey(Agenda, on_delete=models.PROTECT, primary_key=True)
    estatura = models.FloatField('estatura', default=1.60)
    peso = models.IntegerField('peso')
    masa = models.FloatField('Masa Corporal', blank=True, null=True, default=0)
    temperatura = models.FloatField('Temperatura')
    frecRespira = models.IntegerField(
        'Frecuencia Respiratoria', blank=True, null=True, default=0)
    frecCard = models.IntegerField(
        'Frecuencia Cardiaca', blank=True, null=True, default=0)
    porGraCor = models.IntegerField(
        'Porcentaje Grasa Corporal', blank=True, null=True, default=0)
    porMasaMus = models.IntegerField(
        'Porcentaje Masa Muscular', blank=True, null=True, default=0)
    precionArt = models.CharField('Precion Arterial', max_length=10)

    class Meta:
        verbose_name = 'SignosVitales'
        verbose_name_plural = 'SignosVitales'

    def __str__(self):

        # return '{}'.format(self.paciente.pk)
        return '{} {}'.format(self.paciente.paciente, self.paciente.paciente.apellido)

login/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now


class Titulo(models.Model):    
    descripcion = models.CharField(verbose_name='Descricpion', max_length=300, unique=True)    
    class Meta:
        verbose_name = 'Titulo'
        verbose_name_plural = 'Titulos'        

    def __str__(self):
        return '{}'.format(self.descripcion)

class Provincia(models.Model):
    descripcion=models.CharField(verbose_name='Descripcion', max_length=100)
    estado=models.BooleanField(default=True)

    class Meta:
        verbose_name='Provincia'
        verbose_name_plural='Provincias'
    def __str__(self):
        return '{}'.format(self.descripcion)
    
class Ciudad(models.Model):
    provincia=models.ForeignKey(Provincia, on_delete=models.PROTECT)
    descripcion=models.CharField(verbose_name='Descripcion', max_length=100)
    estado=models.BooleanField(default=True)

    class Meta:
        verbose_name='Ciudad'
        verbose_name_plural='Ciudades'

    def __str__(self):
        return '{}'.format(self.descripcion)

class Profesion(models.Model):    
    descripcion=models.CharField(verbose_name='Descripcion', max_length=100, unique=True)
    estado=models.BooleanField(default=True)

    class Meta:
        verbose_name='Profesion'
        verbose_name_plural='Profesiones'

    def __str__(self):
        return '{}'.format(self.descripcion)

class Persona(models.Model):
    tipo_sexo =(('N', 'Ninguno'), ('M', 'Masculino'), ('F', 'Femenino'))
    estado_civil=(('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viudo'), ('U', 'Union Libre'))
    cedula=models.CharField('Cedula', max_length=13, unique=True)
    nombre=models.CharField(max_length=100, verbose_name='Nombres')
    apellido=models.CharField(max_length=100, verbose_name='Apellidos')
    nacimiento=models.DateField('Fecha Nacimiento', blank=True, null=True)
    sexo=models.CharField('Sexo', choices=tipo_sexo, default='N', max_length=1)
    civil=models.CharField('Estado Civil', choices=estado_civil, default='S', max_length=1)
    profesion=models.ManyToManyField(Profesion)
    titulo=models.ManyToManyField(Titulo)
    provincia=models.ForeignKey(Provincia, on_delete=models.PROTECT, blank=True, null=True)
    ciudad=models.ForeignKey(Ciudad, on_delete=models.PROTECT, blank=True, null=True)
    direccion=models.CharField('Direccion', max_length=100, blank=True, null=True)
    telefono=models.CharField('Telefono', max_length=100, blank=True, null=True)
    email=models.EmailField('Correo', max_length=100, blank=True, null=True)
    foto=models.ImageField('Foto', upload_to='fotos/', blank=True, null=True)

    class Meta:
        abstract=True

class Sangre(models.Model):    
    tipo=models.CharField(verbose_name='Tipo de Sangre', max_length=20, unique=True)
    estado=models.BooleanField(default=True)

    class Meta:
        verbose_name='Tipo de Sangre'
        verbose_name_plural='Tipos de Sangre'

    def __str__(self):
        return '{}'.format(self.tipo)


class Paciente(Persona):
    sangre=models.ForeignKey(
        Sangre, on_delete=models.PROTECT, blank=True, null=True
    )
    hijos=models.IntegerField('No. hijos', default=0)
    estado=models.BooleanField(default=True)

    class Meta:
        verbose_name='Paciente'
        verbose_name_plural='Pacientes'

    def __str__(self):
            return '{}'.format(self.nombre)

class Agenda(models.Model):
    paciente=models.ForeignKey(Paciente, on_delete=models.PROTECT)
    fecha=models.DateField(
        'Fecha de Agenda', blank=True, null=True, default=now
    )
    hora=models.TimeField('Hora', default=now().date())
    motivo=models.CharField('Motivo de Consulta', max_length=100)
    estado=models.BooleanField(default=True)

    class Meta:
        verbose_name='Agenda'
        verbose_name_plural='Agendas'

templates/core/cita.html
{% extends 'menu.html' %}


{% block main %}
{% load static %}

<class class="container-fluid">


    <div class="card">
        <div class="card-header text-light" style="background: #E4E4E4;">
            <div class="row">
                <div class="col-md-8">
                    <h3 id="titulo" class="font-weight-bold" style="color: #000000;">Cita</h3>
                </div>
                <div class="col-md-4 ">
                    <a href="{% url 'base:crear_cita' %}" class="btn btn-primary float-right">Nueva Cita</a>
                </div>

            </div>
        </div>
        <div class="card-body">

            <form class="row">

                <div class="col-md-8">
                    <input class="form-control mr-2 bg-secondary text-danger font-weight-bold "
                        placeholder="Texto a Buscar" name="nombre" value={{nombre}}>
                </div>
                <div class="col-md-4 ">
                    <button class="btn btn-primary" type="submit">Buscar</button>
                </div>
            </form>

            <div class="row pt-2">
                <div class="col table-responsive">
                    <table class="table table-striped table-hover table-sm  table-bordered ">

                        <thead>
                            <tr>
                                <th class="text-center">Cedula</th>
                                <th class="text-center">Paciente</th>
                                <th class="text-center">Medico</th>
                                <th class="text-center">Fecha</th>
                                <th class="text-center">Hora</th>
                                <th class="text-center">Estado</th>
                                <th class="text-center">Acciones</th>
                            </tr>

                        </thead>
                        <tbody id="tabla">


                            {% for cita in cita%}
                            <tr>
                                <td class="text-center">{{ cita.paciente.cedula }}</td>

                                <td class="text-center"><span> {{ cita.paciente.nombre | capfirst }} &nbsp
                                        {{ cita.paciente.apellido | capfirst }} </span> </td>
                                <td class="text-center">{{ cita.doctor.nombre | capfirst }} &nbsp
                                    {{ cita.doctor.apellido | capfirst }}</td>
                                <td class="text-center"> {{ cita.fecha }} </td>
                                <td class="text-center"> {{ cita.hora }} </td>



                                <!-- <td class="text-center"> <input type="checkbox" id="valid"  > </td> -->

                                {% if cita.estado == True %}
                                <td class="text-center"> <input type="checkbox" checked
                                        onclick="javascript: return false;"> </td>
                                {% else %}
                                <td class="text-center"> <input type="checkbox" onclick="javascript: return false;">
                                </td>
                                {% endif %}






                                <td class="text-center"><a class="btn btn-primary btn-sm"
                                        href="{% url 'base:editar_cita' cita.id %}">Editar</a>
                                        <a class="btn btn-primary btn-sm"
                                            href="{% url 'base:signos' %}">Signos Vitales</a>
                                    <a rel="action" data-json='{"accion":"elim" ,"id":"{{cita.id}}"}'
                                        class="btn btn-danger btn-sm" href="#">Eliminar</a>
                                </td>
                            </tr>
                            {% empty %}
                            <div class="alert alert-warning alert-dismissible fade show mt-2" role="alert">
                                <strong>Mensaje del Sistema!</strong> No existen Citas registrados
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            {% endfor %}


                        </tbody>
                    </table>
                </div>
            </div>
            <!-- Menú de paginación -->
            {% if is_paginated %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item ">
                        <a class="page-link"
                            href="?nombre={{nombre}}&page={{ page_obj.previous_page_number }}">&laquo;</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">&laquo;</a>
                    </li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                    {% if i <= page_obj.number|add:2 and i >= page_obj.number|add:-2 %}
                    {% if page_obj.number == i %}
                    <li class="page-item active" style="pointer-events:none">
                        <a href="#" class="page-link">{{ forloop.counter }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a href="?page={{ forloop.counter }}{{ url }}" class="page-link">{{ forloop.counter }}</a>
                    </li>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-item ">
                        <a class="page-link" href="?nombre={{nombre}}&page={{ page_obj.next_page_number }}">&raquo;</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">&raquo;</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
            <!-- Fin del pagineo -->
        </div>
    </div>

</class>

{% endblock %}


{% block frmodal %}
<!-- inicio formulario Modal para Eliminar -->

<div class="modal fade" id="myModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <form name="frmEliminar" id="frmEliminar" method="POST" action="{% url 'base:eliminar_cita' 0 %} ">
                {% csrf_token %}
                <div class="modal-header bg-primary text-light">
                    <h3 class="modal-title ml-5 font-weight-bold">Mensaje Del Sistema</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="id" id="id" value="">
                    <input type="hidden" name="action" value="elim">
                    <div class="h3 text-center">
                        <label class="text-primary font-weight-bold">Esta Seguro De Eliminar la cita:</label>
                        <span class="text-light font-weight-bold badge badge-danger badge-pill"
                            id="descripcion"></span><br>

                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Eliminar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Final Formulario Modal-->


 


{% endblock %}


{% block jscript %}
<script>
    $(function () {

        $('#tabla').on('click', 'a[rel="action"]', function () {
            let data = $(this).data('json'),
                action = data.accion,
                id = data.id;
            let desc = $(this).parents('tr').children('td').eq(1).html();
            $('#descripcion').html(desc);
            $('#frmEliminar #id').val(id);
            $('#myModal').modal('show');
            return;

        });

    })

    function convertir() {
        let titulo = document.getElementById("titulo").innerText
        document.getElementById("titulo").innerText = titulo.toUpperCase()
        alert(titulo)
    }
</script>
{% endblock %}

templates/core/registrar_paciente.html
{% extends 'menu.html' %}

{% block main %}
{% load static %}


<div class="container-fluid">
    <div class="card-header  text-light">
        <div class="row p-3" style="background: gray;">
            <div class="col-md-8">
                <h3 class="font-weight-bold">Mantenimiento de Pacientes</h3>
            </div>
        </div>
    </div>
    <div class="card-body border rounded-top border-dark">
        <div class="col-md-12">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {% if form.errors %}
                <div class="alert alert-warning alert-dismissible fade show mt-2" role="alert">
                    <strong> {{ form.errors}}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}



                <div class="card mx-5" >
                    <!-------Aqui va el color background-color: #EBF5FB---------->
                    <div class="row mx-2 my-3 form-group">
                        <div class="col-9 font-weight-bold text-dark">
                            <div class="row">
                                <div class="form-group col-12 col-md-6">
                                    <label for="{{form.nombre.id_for_label }}">Nombre: </label>
                                    {{ form.nombre }}
                                </div>
                                <div class="form-group col-12 col-md-6">
                                    <label for="{{form.cedula.id_for_label }}">Cedula: </label>
                                    {{ form.cedula }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-12 col-md-6">
                                    <label for="{{form.apellido.id_for_label }}">Apellido: </label>
                                    {{ form.apellido }}
                                </div>
                                <div class="form-group col-12 col-md-6">
                                    <label for="{{form.direccion.id_for_label }}">Direccion: </label>
                                    {{ form.direccion }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-12 col-md-6">
                                    <label for="{{form.nacimiento.id_for_label }}">Fecha Nacimiento: </label>
                                    {{ form.nacimiento }}
                                </div>
                                <div class="form-group col-12 col-md-6">
                                    <label for="{{form.telefono.id_for_label }}">Telefono: </label>
                                    {{ form.telefono }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-12 col-md-6">
                                    <label for="{{form.sexo.id_for_label }}">Sexo: </label>
                                    {{ form.sexo }}
                                </div>
                                <div class="form-group col-12 col-md-6">
                                    <label for="{{form.email.id_for_label }}">email: </label>
                                    {{ form.email }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-12 col-md-6 ">
                                    <label  for="{{form.civil.id_for_label }}">civil:
                                    </label>
                                    {{ form.civil }}
                                </div>
                                <div class="form-group col-12 col-md-6">
                                    <label for="{{form.sangre.id_for_label }}">Tipo de Sangre: </label>
                                    {{ form.sangre }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-12 col-md-6">
                                    <label for="{{form.hijos.id_for_label }}">Numero de Hijos: </label>
                                    {{ form.hijos }}
                                </div>
                                <div class="form-group col-12 col-md-6">
                                    <label for="{{form.estado.id_for_label }}">Estado: </label>
                                    {{ form.estado }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-12 col-md-6">
                                    <label for="{{form.profesion.id_for_label }}">Profesion: </label>
                                    {{ form.profesion }}
                                </div>
                                <div class="form-group col-12 col-md-6">
                                    <label for="{{form.titulo.id_for_label }}">Titulo: </label>
                                    {{ form.titulo }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-12 col-md-6">
                                    <label for="{{form.ciudad.id_for_label }}">Ciudad: </label>
                                    {{ form.ciudad }}
                                </div>
                            </div>

                        </div>
                        <div class="col-3">
                            <div class="row justify-content-center">
                                <div class="card mt-4 text-dark" style="width: 15rem;">
                                    <img class="card-img-top" src="{% static 'img/sinfoto.png' %}" alt="Card image"
                                        id="preview_foto">
                                    <div class="card-body">
                                        <h5 class="card-title font-weight-lighter">Imagen de perfil</h5>
                                        <p class="card-text">
                                            <div class="form-group" onclick="preview( {{form.foto.id_for_label}} )">
                                                {{ form.foto }}
                                            </div>
                                        </p>
                                        {% comment %} <p class="card-text"><button type="submit"
                                                class="btn botones">Guardar</button></p> {% endcomment %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class=" form-group row justify-content-center my-4">
                    <div class="col-4 col-md-2">
                        <a href="{% url 'base:paciente' %}"><input class="btn bg-danger w-100 text-light float-right"
                                value="Cancelar"></input></a>
                    </div>
                    <div class="col-4 col-md-2">
                        <button type="submit" class="btn botones w-100 float-left">Guardar</button>
                    </div>
                </div>



            </form>
        </div>


    </div>

</div>


{% endblock main %}

{% block jscript %}
<script>
    function preview() {

        const $seleccionArchivos = document.querySelector("#id_logo"),
            $imagenPrevisualizacion = document.querySelector("#preview_logo"),
            $imagen = document.querySelector("#preview_foto");
        $seleccionFoto = document.querySelector("#id_foto");
        $seleccionFoto.addEventListener("change", () => {
            const objectURL = URL.createObjectURL($seleccionFoto.files[0]);
            $imagen.src = objectURL;
        });
    }
    preview();


</script>
{% endblock jscript %}