appclinica/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.urls import path, include
#from login.views import *
from appatencion.views import menuView, opcionesView
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('appatencion/', include('appatencion.urls')),
    path('menu/', login_required(menuView.as_view()), name='menu'),
    #--------------------------------------- login
    path('', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('opciones/', opcionesView.as_view(), name='opciones'),
    path('base/', include('appcore.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

appcore/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import * #PacienteView, CrearPacienteView, EditarPacienteView, EliminarPacienteView, DoctorView, EditarDoctorView, EliminarDoctorView, CrearDoctorView, IndexView
app_name = 'base'
urlpatterns = [
    path('paciente/', PacienteView.as_view(), name='paciente'),
    path('crear_paciente/', CrearPacienteView.as_view(), name='crear_paciente'),
    path('editar_paciente/<int:pk>/',
         EditarPacienteView.as_view(), name='editar_paciente'),
    path('eliminar_paciente/<int:pk>/',
         EliminarPacienteView.as_view(), name='eliminar_paciente'),

    path('cita/', CitaView.as_view(), name='cita'),
    path('crear_cita/', CrearCitaView.as_view(), name='crear_cita'),
    path('editar_cita/<int:pk>/',
         EditarCitaView.as_view(), name='editar_cita'),
    path('eliminar_cita/<int:pk>/',
         EliminarCitaView.as_view(), name='eliminar_cita'),


    path('signos/', SignosView.as_view(), name='signos'),
    path('crear_signo/',
         crearSignoView.as_view(), name='crear_signo'),
    path('editar_signo/<int:pk>/',
         EditarSignoView.as_view(), name='editar_signo'),


     path('', IndexView.as_view(), name='index'),  
     path('doctor_view/', login_required(DoctorView.as_view()), name='doctor_view'), 
     path('doctor/', CrearDoctorView.as_view(), name='doctor'), 
     path('doctor_edit/<int:pk>/', EditarDoctorView.as_view(), name='doctor_edit'),
     path('doctor_delete/<int:pk>/', EliminarDoctorView.as_view(), name='doctor_delete'),

]

login/urls.py
from django.contrib import admin
from django.urls import path
from login.views import LoginView
from django.conf import settings
app_name = "login"
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
]

appcore/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, date


class Provincia(models.Model):
    descripcion = models.CharField(verbose_name='Descripcion', max_length=100)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Provincia'
        verbose_name_plural = 'Provincias'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Ciudad(models.Model):
    provincia = models.ForeignKey(Provincia, on_delete=models.PROTECT)
    descripcion = models.CharField(verbose_name='Descripcion', max_length=100)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Ciudad'
        verbose_name_plural = 'Ciudades'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Profesion(models.Model):
    descripcion = models.CharField(
        verbose_name='Descripcion', max_length=100, unique=True)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Profesion'
        verbose_name_plural = 'Profesiones'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Titulo(models.Model):
    descripcion = models.CharField(
        verbose_name='Descripcion', max_length=100, unique=True)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Titulo'
        verbose_name_plural = 'Titulos'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Persona(models.Model):
    tipo_sexo = (('N', 'Ninguno'), ('M', 'Masculino'), ('F', 'Femenino'))
    estado_civil = (('S', 'Soltero'), ('C', 'Casado'),
                    ('D', 'Divorciado'), ('V', 'Viudo'), ('U', 'Union'))
    cedula = models.CharField('Cedula', max_length=13, unique=True)
    nombre = models.CharField(max_length=100, verbose_name='Nombres')
    apellido = models.CharField(max_length=100, verbose_name='Apellidos')
    nacimiento = models.DateField('Fecha Nacimiento', blank=True, null=True)
    sexo = models.CharField('sexo', choices=tipo_sexo,
                            default='N', max_length=1)
    civil = models.CharField(
        'Estado civil', choices=estado_civil, default='S', max_length=1)
    profesion = models.ManyToManyField(Profesion)
    titulo = models.ManyToManyField(Titulo)
    provincia = models.ForeignKey(
        Provincia, on_delete=models.PROTECT, blank=True, null=True)
    ciudad = models.ForeignKey(
        Ciudad, on_delete=models.PROTECT, blank=True, null=True)
    direccion = models.CharField(
        'Direccion', max_length=100, blank=True, null=True)
    telefono = models.CharField(
        'Telefono', max_length=100, blank=True, null=True)
    email = models.EmailField('Correo', max_length=100, blank=True, null=True)
    foto = models.ImageField('Foto', upload_to='fotos/', blank=True, null=True)

    class Meta:
        abstract = True

    def get_foto(self):
        try:
            return str(self.foto.url)
        except:
            pass
        return None


class Sangre(models.Model):
    tipo = models.CharField('Tipo de Sangre', max_length=20, unique=True)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Tipo de Sangre'
        verbose_name_plural = 'Tipos de Sangre'

    def __str__(self):
        return '{}'.format(self.tipo)


class Paciente(Persona):
    sangre = models.ForeignKey(
        Sangre, on_delete=models.PROTECT, blank=True, null=True)
    hijos = models.IntegerField('No.hijos', default=0)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'

    def __str__(self):
        return '{}'.format(self.nombre)


class Horario(models.Model):
    d_semana = {(0, 'Domingo'), (1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'),
                (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')}
    dia = models.IntegerField('Dia', choices=d_semana, default=1)
    desde = models.TimeField('Desde', blank=True, null=True)
    hasta = models.TimeField('Hasta', blank=True, null=True)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Dia'
        verbose_name_plural = 'Dias'

    def __str__(self):
        return '{}'.format(self.dia)


class Doctor(Persona):
    consultoria = models.CharField(max_length=200)
    lugar = models.CharField(
        verbose_name='Direccion de Consultorio', max_length=100)
    logo = models.ImageField(
        verbose_name='Logo', upload_to='Logos/', blank=True, null=True)
    horario = models.ManyToManyField(Horario)
    registro = models.CharField(verbose_name='Registro Medico', max_length=50)
    duracion = models.IntegerField(
        verbose_name='Duracion de Consulta', default=30)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Doctor'
        verbose_name_plural = 'Doctores'

    def __str__(self):
        return '{}'.format(self.nombre)


class Agenda(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.PROTECT)
    doctor = models.ForeignKey(Doctor, on_delete=models.PROTECT)
    fecha = models.DateField(
        'Fecha de Agenda', blank=True, null=True)
    hora = models.TimeField('Hora', default=datetime.now().time())
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Agenda'
        verbose_name_plural = 'Agendas'

    def __str__(self):
        return '{} {}'.format(self.paciente.nombre, self.paciente.apellido)


# ---------------------------------------------------------------------Sintomas
class Sintoma(models.Model):
    descripcion = models.CharField('Sintoma', max_length=100)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Sintoma'
        verbose_name_plural = 'Sintomas'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Diagnostico(models.Model):
    codigo = models.CharField('Codigo', max_length=100)
    descripcion = models.CharField('Diagnostico', max_length=100)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Diagnostico'
        verbose_name_plural = 'Diagnosticos'

    def __str__(self):
        return '{}'.format(self.descripcion)


class SignosVitales(models.Model):
    paciente = models.ForeignKey(Agenda, on_delete=models.PROTECT, primary_key=True)
    estatura = models.FloatField('estatura', default=1.60)
    peso = models.IntegerField('peso')
    masa = models.FloatField('Masa Corporal', blank=True, null=True, default=0)
    temperatura = models.FloatField('Temperatura')
    frecRespira = models.IntegerField(
        'Frecuencia Respiratoria', blank=True, null=True, default=0)
    frecCard = models.IntegerField(
        'Frecuencia Cardiaca', blank=True, null=True, default=0)
    porGraCor = models.IntegerField(
        'Porcentaje Grasa Corporal', blank=True, null=True, default=0)
    porMasaMus = models.IntegerField(
        'Porcentaje Masa Muscular', blank=True, null=True, default=0)
    precionArt = models.CharField('Precion Arterial', max_length=10)

    class Meta:
        verbose_name = 'SignosVitales'
        verbose_name_plural = 'SignosVitales'

    def __str__(self):

        # return '{}'.format(self.paciente.pk)
        return '{} {}'.format(self.paciente.paciente, self.paciente.paciente.apellido)

login/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now


class Titulo(models.Model):    
    descripcion = models.CharField(verbose_name='Descricpion', max_length=300, unique=True)    
    class Meta:
        verbose_name = 'Titulo'
        verbose_name_plural = 'Titulos'        

    def __str__(self):
        return '{}'.format(self.descripcion)

class Provincia(models.Model):
    descripcion=models.CharField(verbose_name='Descripcion', max_length=100)
    estado=models.BooleanField(default=True)

    class Meta:
        verbose_name='Provincia'
        verbose_name_plural='Provincias'
    def __str__(self):
        return '{}'.format(self.descripcion)
    
class Ciudad(models.Model):
    provincia=models.ForeignKey(Provincia, on_delete=models.PROTECT)
    descripcion=models.CharField(verbose_name='Descripcion', max_length=100)
    estado=models.BooleanField(default=True)

    class Meta:
        verbose_name='Ciudad'
        verbose_name_plural='Ciudades'

    def __str__(self):
        return '{}'.format(self.descripcion)

class Profesion(models.Model):    
    descripcion=models.CharField(verbose_name='Descripcion', max_length=100, unique=True)
    estado=models.BooleanField(default=True)

    class Meta:
        verbose_name='Profesion'
        verbose_name_plural='Profesiones'

    def __str__(self):
        return '{}'.format(self.descripcion)

class Persona(models.Model):
    tipo_sexo =(('N', 'Ninguno'), ('M', 'Masculino'), ('F', 'Femenino'))
    estado_civil=(('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viudo'), ('U', 'Union Libre'))
    cedula=models.CharField('Cedula', max_length=13, unique=True)
    nombre=models.CharField(max_length=100, verbose_name='Nombres')
    apellido=models.CharField(max_length=100, verbose_name='Apellidos')
    nacimiento=models.DateField('Fecha Nacimiento', blank=True, null=True)
    sexo=models.CharField('Sexo', choices=tipo_sexo, default='N', max_length=1)
    civil=models.CharField('Estado Civil', choices=estado_civil, default='S', max_length=1)
    profesion=models.ManyToManyField(Profesion)
    titulo=models.ManyToManyField(Titulo)
    provincia=models.ForeignKey(Provincia, on_delete=models.PROTECT, blank=True, null=True)
    ciudad=models.ForeignKey(Ciudad, on_delete=models.PROTECT, blank=True, null=True)
    direccion=models.CharField('Direccion', max_length=100, blank=True, null=True)
    telefono=models.CharField('Telefono', max_length=100, blank=True, null=True)
    email=models.EmailField('Correo', max_length=100, blank=True, null=True)
    foto=models.ImageField('Foto', upload_to='fotos/', blank=True, null=True)

    class Meta:
        abstract=True

class Sangre(models.Model):    
    tipo=models.CharField(verbose_name='Tipo de Sangre', max_length=20, unique=True)
    estado=models.BooleanField(default=True)

    class Meta:
        verbose_name='Tipo de Sangre'
        verbose_name_plural='Tipos de Sangre'

    def __str__(self):
        return '{}'.format(self.tipo)


class Paciente(Persona):
    sangre=models.ForeignKey(
        Sangre, on_delete=models.PROTECT, blank=True, null=True
    )
    hijos=models.IntegerField('No. hijos', default=0)
    estado=models.BooleanField(default=True)

    class Meta:
        verbose_name='Paciente'
        verbose_name_plural='Pacientes'

    def __str__(self):
            return '{}'.format(self.nombre)

class Agenda(models.Model):
    paciente=models.ForeignKey(Paciente, on_delete=models.PROTECT)
    fecha=models.DateField(
        'Fecha de Agenda', blank=True, null=True, default=now
    )
    hora=models.TimeField('Hora', default=now().date())
    motivo=models.CharField('Motivo de Consulta', max_length=100)
    estado=models.BooleanField(default=True)

    class Meta:
        verbose_name='Agenda'
        verbose_name_plural='Agendas'

login/views.py
from django.shortcuts import redirect, render
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from .forms import DoctorForm
from django.urls.base import reverse_lazy
from .models import Doctor

# Create your views here.  form.cleaned_data['renewal_date']
class IndexView(TemplateView):
    template_name = "index.html"
    
#--------------------------------------------------------------------------------------Sintomas

# class CrearSintomaView(CreateView):
#     model = Sintoma   
#     template_name = "diagnostico.html"
#     form_class = DoctorForm
#     success_url = reverse_lazy('menu')
#     context_object_name = "Sintomas"

templates/doctor_view.html
{% extends "menu.html" %}

{% block main %}
{% load static %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header" data-background-color="blue">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item"><a href="#">Mantenimientos</a></li>
                        <li class="breadcrumb-item active " aria-current="page">Doctor</li>
                    </ol>
                </nav>
            </div>
            <div class="container">
                <div class="table-responsive-sm"><br>
                    <form class="row" style="margin-bottom:5px">
                        <div class="col-5 col-md-3">
                            <input class="form-control mr-2" placeholder="Nombre a Buscar" name="nombre"
                                value={{nombre}}>
                        </div>
                        <div class="col-2 col-md-1 justify-content-start">
                            <button type="submit" class="btn botones float-md-right float-left">Buscar</button>
                        </div>
                        <div class="col-5 col-md-8 justify-content-end">
                            <a href="{% url 'base:doctor' %}" class="btn botones float-right w80"><b>Nuevo</b></a>
                        </div>
                    </form>
                    <table class="table table-bordered table-hover">
                        <thead>


                            <thead class="thead-dark">
                                <th scope="col" class="text-center">ID</th>
                                <th scope="col" class="text-center">Foto</th>
                                <th scope="col" class="text-center">Nombres</th>
                                <th scope="col" class="text-center">Sexo</th>
                                <th scope="col" class="text-center">Ciudad</th>
                                <th scope="col" class="text-center">Email</th>
                                <th scope="col" class="text-center">Consultoria</th>
                                <th scope="col" class="text-center">Horario</th>
                                <th scope="col" class="text-center">Duracion</th>
                                <th scope="col" class="text-center">Acción</th>
                            </thead>
                        </thead>
                        <tbody id="tabla shadow">
                            {% for data in datos %}
                            <tr>
                                <th class="text-center">{{ data.id }}</th>
                                {% if  data.foto %}
                                <td class="text-center"><img src="{{ data.foto.url }}" class="img rounded-circle"
                                        width="40px" height="40px"></td>
                                {% else %}
                                <td class=" text-center"><img src="{% static 'img/sinfoto.png' %}"
                                        class="img-thumbnail rounded-circle" width="40px" height="40px"></td>
                                {% endif %}
                                <td class="text-center">{{ data.nombre | capfirst }} &nbsp
                                    {{ data.apellido | capfirst }}</td>
                                {% if data.sexo == 'M' %}
                                <td class="text-center"><span
                                        class="badge badge-pill badge-success">{{data.sexo}}</span>
                                </td>
                                {% else %}
                                <td class="text-center"><span class="badge badge-pill badge-danger">{{data.sexo}}</span>
                                </td>
                                {% endif %}
                                <td class="text-center">{{data.ciudad.descripcion}}</td>
                                <td class="text-center">{{data.email}}</td>
                                <td class="text-center">{{data.consultoria}}</td>
                                <td class="text-center">{{data.horario.dia }} &nbsp {{ data.horario.desde }} &nbsp
                                    {{data.horario.hasta}}</td>
                                <td class="text-center">{{data.duracion}}</td>
                                <td style="width:130px" class="text-center">
                                    <a href="{% url 'base:doctor_edit' data.id %}" class="btn btn-warning btn-sm w-25">
                                        <span class='fa fa-edit fa-lg'></span>
                                    </a>
                                    <a rel="action" data-json='{"accion":"elim" ,"id":"{{data.id}}"}'
                                        class="btn btn-danger btn-sm" href="#">Eliminar</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>


                    <!-- Menú de paginación -->
                    <!-- Fin del pagineo -->


                    <div class="row">
                        <div class="col-4 float-left">
                            <label class="text-muted">
                                Mostrando 3 de {{ datos | length }} registros
                            </label>
                        </div>
                        <div class="col-4"></div>
                        <div class="col-4">
                            {% if is_paginated %}
                            <nav aria-label="..." class="float-right">
                                <ul class="pagination justify-content-center">
                                    {% if page_obj.has_previous %}
                                    <li class="page-item ">
                                        <a class="page-link"
                                            href="?nombre={{nombre}}&page={{ page_obj.previous_page_number }}">Previous</a>
                                    </li>
                                    {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                                    </li>
                                    {% endif %}
                                    {% for i in paginator.page_range %}
                                    {% if i <= page_obj.number|add:2 and i >= page_obj.number|add:-2 %}
                                    {% if page_obj.number == i %}
                                    <li class="page-item active" style="pointer-events:none">
                                        <a href="#" class="page-link">{{ forloop.counter }}</a>
                                    </li>
                                    {% else %}
                                    <li class="page-item">
                                        <a href="?page={{ forloop.counter }}{{ url }}"
                                            class="page-link">{{ forloop.counter }}</a>
                                    </li>
                                    {% endif %}
                                    {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                    <li class="page-item ">
                                        <a class="page-link"
                                            href="?nombre={{nombre}}&page={{ page_obj.next_page_number }}">Next</a>
                                    </li>
                                    {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="#" tabindex="-1">Next</a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </nav>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--<p class='alert alert-danger'>Si No hay clientes registrados presenta esta alerta</p>-->
    </div>
</div>
{% endblock %}

{% block frmodal %}
<!-- inicio formulario Modal para Eliminar -->
<div class="modal fade" id="myModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <form name="frmEliminar" id="frmEliminar" method="POST" action="{% url 'base:doctor_delete' 0 %} ">
                {% csrf_token %}
                <div class="modal-header bg-primary text-light">
                    <h3 class="modal-title ml-5 font-weight-bold">Mensaje Del Sistema</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="id" id="id" value="">
                    <input type="hidden" name="action" value="elim">
                    <div class="h3 text-center">
                        <label class="text-primary font-weight-bold">Esta Seguro De Eliminar El Paciente:</label>
                        <span class="text-light font-weight-bold badge badge-danger badge-pill"
                            id="descripcion"></span><br>

                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Eliminar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Final Formulario Modal-->
{% endblock frmodal %}

{% block jscript %}
<script>
    $(function () {
        $('#tabla').on('click', 'a[rel="action"]', function () {
            let data = $(this).data('json'),
                action = data.accion,
                id = data.id;
            let desc = $(this).parents('tr').children('td').eq(1).html();
            $('#descripcion').html(desc);
            $('#frmEliminar #id').val(id);
            $('#myModal').modal('show');
            return;
        });
    })
</script>
{% endblock %}

templates/menu.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {% load static%}
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}">
  <script src="https://kit.fontawesome.com/39ba0a2a82.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js">
  <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
  <title>menu</title>
</head>

<body>



  <div class="d-flex">

    <!-- menu -->
    <div id="sidebar-container" class="bg-primary">
      <div class="logo">
        <h4 class="text-light font-weight-bold"><img src="/media/fotos/logo.png" class="img-fluid mr-2 foto" alt="">
        </h4>
      </div>
      <div class="menu">
        <a href="{% url  'menu' %}" class="d-block p-4 text-light"> <i class="fas fa-home fa-lg mr-2"></i>
          Inicio</a>
        <a href="{% url 'base:paciente' %}" class="d-block p-4 text-light"> <i
            class="fas fa-user-injured fa-lg mr-2"></i> Pacientes</a>
        <a href="{% url 'base:cita' %}" class="d-block p-4 text-light"> <i
            class="fas fa-notes-medical fa-lg mr-2"></i> Consulta</a>
        <a href="{% url 'base:crear_cita' %}" class="d-block p-4 text-light"> <i class="fas fa-clipboard-list fa-lg mr-2"></i>
          Agenda</a>
        <a href="{% url 'base:doctor_view' %}" class="d-block p-4 text-light"> <i class="fas fa-user-md fa-lg mr-2"></i> Doctor</a>
        <a href="/admin" class="d-block p-4 text-light"> <i class="fas fa-cogs fa-lg mr-2"></i>
          Configuracion</a>
      </div>
    </div>
    <!-- termina menu -->

    <div class="w-100">

      <!-- navbar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <a style="cursor: default;" class="navbar-brand d-inline-block" href="#">Centro De Especialidades JVG</a>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false">
                  <img src="/media/fotos/george.jpg" class="img-fluid rounded-circle mr-2 avatar" alt="">
                  Dr George Calderon
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Perfil</a>
                  <a class="dropdown-item" href="#">Cambiar contrseña</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">log out</a>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- cierra navbar -->

      <div id="content">

        {% block main %}

        {% endblock %}
        

      </div>


    </div>
  </div>

  {% block frmodal %}

  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
  </script>

  {% block jscript %}

  {% endblock %}

</body>

</html>